initialize_analysis <-function(path){
  if (!file.exists(paste(path,"FUN_NORM_DATA",sep="/"))system(paste( "mkdir",paste(path,"FUN_NORM_DATA",sep="/"), sep = " "))
  if (!file.exists(paste(path,"RAW_DATA",sep="/"))              system(paste( "mkdir",paste(path,"RAW_DATA",sep="/"), sep = " "))
  if (!file.exists(paste(path,"PHENOTYPE_DATA",sep="/"))        system(paste( "mkdir",paste(path,"PHENOTYPE_DATA",sep="/"), sep = " "))
  if (!file.exists(paste(path,"ANNOTATION_DATA",sep="/"))       system(paste( "mkdir",paste(path,"ANNOTATION_DATA",sep="/"), sep = " "))
  if (!file.exists(paste(path,"COVARIABLE_DATA",sep="/"))       system(paste( "mkdir",paste(path,"COVARIABLE_DATA",sep="/"), sep = " "))
  if (!file.exists(paste(path,"QC_REPORT",sep="/"))             system(paste( "mkdir",paste(path,"QC_REPORT",sep="/"), sep = " "))
  if (!file.exists(paste(path,"IDAT",sep="/"))                  system(paste( "mkdir",paste(path,"IDAT",sep="/"), sep = " "))
  if (!file.exists(paste(path,"PCA_ANALYSIS",sep="/"))          system(paste( "mkdir",paste(path,"PCA_ANALYSIS",sep="/"), sep = " "))
  if (!file.exists(paste(path,"RDA_ANALYSIS",sep="/"))          system(paste( "mkdir",paste(path,"RDA_ANALYSIS",sep="/"), sep = " "))
  if (!file.exists(paste(path,"DOCUMENTATION",sep="/"))         system(paste( "mkdir",paste(path,"DOCUMENTATION",sep="/"), sep = " "))
  if (!file.exists(paste(path,"BIN",sep="/"))                   system(paste( "mkdir",paste(path,"BIN",sep="/"), sep = " "))
  if (!file.exists(paste(path,"REPLICATION_ANALYSIS",sep="/"))  system(paste( "mkdir",paste(path,"REPLICATION_ANALYSIS",sep="/"), sep = " "))
  if (!file.exists(paste(path,"FILTERED_DATA",sep="/"))         system(paste( "mkdir",paste(path,"FILTERED_DATA",sep="/"), sep = " "))
  if (!file.exists(paste(path,"TEMP",sep="/"))                  system(paste( "mkdir",paste(path,"TEMP",sep="/"), sep = " "))
  if (!file.exists(paste(path,"STATISTICAL_ANALYSIS",sep="/"))  system(paste( "mkdir",paste(path,"STATISTICAL_ANALYSIS",sep="/"), sep = " "))
  if (!file.exists(paste(path,"CLUSTERING_ANALYSIS",sep="/"))   system(paste( "mkdir",paste(path,"CLUSTERING_ANALYSIS",sep="/"), sep = " "))
  if (!file.exists(paste(path,"FUNCTIONAL_ANALYSIS_GO_PATHWAY",sep="/"))      system(paste( "mkdir",paste(path,"FUNCTIONAL_ANALYSIS_GO_PATHWAY",sep="/"), sep = " "))
  if (!file.exists(paste(path,"FUNCTIONAL_ANALYSIS_ANNOTATION",sep="/"))      system(paste( "mkdir",paste(path,"FUNCTIONAL_ANALYSIS_ANNOTATION",sep="/"), sep = " "))
}#
